### ISSUE TITLE
how to use it in wordpress?

### ISSUE THREAD

**Issue by alexlii1971** [johncoates/SafariInlineVideos#1]
Hello, 

Is it possible to use it in wordpress a plugin?

Alex

**Comment by JohnCoates** [comment]
It's not for that, but I do have a solution for you if you're interested. It wouldn't be free of cost however

**Comment by alexlii1971** [comment]
thanks, that would be great, since there are millions of wordpress sites, and I think it would be a much popular plugin if you like to do that.

Alex

**Comment by JohnCoates** [comment]
Is this a solution that you need urgently or that you're willing to pay development time for?

**Comment by alexlii1971** [comment]
well, not so ugrently, since it is quite basic function.

Alex

**Comment by JohnCoates** [comment]
Okay. Just so you know the code on this repository is to enable this feature on an iPhone, regardless of how a website formats their videos.

The solution you're interested in would be more along the lines of https://github.com/bfred-it/iphone-inline-video

I have a better solution as well, but the code is private and sells for $1,000 a copy. It's geared for companies where this feature is very important.
